name: Update Website

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'website skip')"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy Website 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: registry.build
