name: Deploy

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Fetch data
        run: |
          go run tools/update.go --clone=true
      - name: Update flags
        run: |
          go run settings/settings.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update data
      - name: Build Website
        run: |
          bazel build //website
          rm -rf website/build
          mkdir -p website/build
          cd website/build
          tar -xf ../../bazel-bin/website/website.tar
          touch .nojekyll
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: website/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
